language: cpp

sudo: required
dist: xenial
osx_image: xcode10.3

os:
  - linux
  - osx

if: tag IS blank

env:
  - TARGET=linux64 ENABLE_WEBKIT=OFF
  - TARGET=linux64 ENABLE_WEBKIT=ON
  - TARGET=macos64 ENABLE_WEBENGINE=OFF
  - TARGET=macos64 ENABLE_WEBENGINE=ON

matrix:
  exclude:
    - env: TARGET=linux64 ENABLE_WEBKIT=OFF
      os: osx
    - env: TARGET=linux64 ENABLE_WEBKIT=ON
      os: osx
    - env: TARGET=macos64 ENABLE_WEBENGINE=OFF
      os: linux
    - env: TARGET=macos64 ENABLE_WEBENGINE=ON
      os: linux

install:
  - ./tests/travis-ci/install-build-depends.sh

script:
  - ./tests/travis-ci/build-and-test.sh
