language: cpp

dist: xenial
sudo: required

os:
  - linux
  - osx

env:
  - TARGET=linux64 ENABLE_WEBENGINE=OFF
  - TARGET=linux64 ENABLE_WEBENGINE=ON
  - TARGET=macos64 ENABLE_WEBENGINE=OFF
  - TARGET=macos64 ENABLE_WEBENGINE=ON

matrix:
  exclude:
    - env: TARGET=linux64 ENABLE_WEBENGINE=OFF
      os: osx
    - env: TARGET=linux64 ENABLE_WEBENGINE=ON
      os: osx
    - env: TARGET=macos64 ENABLE_WEBENGINE=OFF
      os: linux
    - env: TARGET=macos64 ENABLE_WEBENGINE=ON
      os: linux

install:
  - ./tests/travis-ci/install-build-depends.sh

script:
  - ./tests/travis-ci/build-and-test.sh
